# Generated by Django 5.0.7 on 2024-09-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rdate", models.DateField(verbose_name="Release Date")),
                ("moviename", models.CharField(max_length=30, verbose_name="Movie")),
                ("hero", models.CharField(max_length=30, verbose_name="Hero Name")),
                (
                    "heroine",
                    models.CharField(max_length=30, verbose_name="Heroine Name"),
                ),
                ("rating", models.IntegerField(verbose_name="Rating")),
            ],
        ),
    ]
