# Generated by Django 5.0.7 on 2024-10-01 08:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FilterDemo",
            new_name="FilterModel",
        ),
    ]
